spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:
      true

  datasource:
    url: jdbc:mysql://hostpitalchanneling.mysql.database.azure.com:3306/hospital_management_system?useSSL=true&serverTimezone=UTC&failOverReadOnly=false&createDatabaseIfNotExist=true
    username:
      HCSadmin
    password:
      vykguf-5roTmu-wanvim
    driver-class-name:
      com.mysql.cj.jdbc.Driver


#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql:
#      true
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/hospitalmanagement?createDatabaseIfNotExist=true
#    username:
#      root
#    password:
#      4dhr@TY8
#    driver-class-name:
#      com.mysql.cj.jdbc.Driver